version: '3.7'

services:
  main:
    container_name: main
    build: ./
    restart: always
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      - LOG_FORMAT=simple
      - RPC_URL=<rpc url>
      - RESUBMIT_TX_TIMEOUT_SECONDS=300
      - ERROR_TX_TIMEOUT_SECONDS=60
      - WALLET_PRIVATE_KEY
    ports:
      - '3000:3000'
