name: Tests and checks
on: pull_request
jobs:
  test:
    name: App tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
        env:
          RPC_URL: ${{ secrets.TESTS_RPC_URL }}
          WALLET_PRIVATE_KEY: ${{ secrets.TESTS_PRIVATE_KEY }}

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
